function results = main_pilot
base = fileparts(mfilename('fullpath'));

validate_best_response;

results = main_scalability(struct( ...
    'sizes',200:200:10000, ...
    'repetitions',1, ...
    'maxSweeps',5000, ...
    'timeLimitSeconds',1800, ...
    'gapEvery',5, ...
    'epsilon',1e-6, ...
    'outputDir',fullfile(base,'pilot_results_extended')));
end