function te_write_tables(a,o)
summary = cell(0,8); distribution = cell(0,8);
for ni = 1:numel(o.networks)
    name = o.networks{ni}; r = a.(name);
    for ti = 1:numel(o.testRates)
        for pi = 1:numel(o.attackRates)
            summary(end+1,:) = {name,o.testRates(ti),o.attackRates(pi), ...
                r.meanTrust(pi,ti,1),r.stdTrust(pi,ti,1), ...
                r.meanTrust(pi,ti,2),r.stdTrust(pi,ti,2),o.repetitions}; %#ok<AGROW>
        end
        for b = 1:numel(o.binEdges)-1
            distribution(end+1,:) = {name,o.testRates(ti),o.distributionPC, ...
                o.binEdges(b),o.binEdges(b+1),r.histPercent(b,ti,1), ...
                r.histPercent(b,ti,2),b==numel(o.binEdges)-1}; %#ok<AGROW>
        end
    end
end
writetable(cell2table(summary,'VariableNames',{'Network','PT','PC','NormalMean', ...
    'NormalSD','CompromisedMean','CompromisedSD','Repetitions'}),fullfile(o.outputDir,'mean_trustworthiness.csv'));
writetable(cell2table(distribution,'VariableNames',{'Network','PT','PC','BinLeft', ...
    'BinRight','NormalPercent','CompromisedPercent','RightEndpointIncluded'}),fullfile(o.outputDir,'trust_distribution.csv'));
fid = fopen(fullfile(o.outputDir,'figure_captions.txt'),'w');
assert(fid>=0,'Cannot create caption file.'); cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
pt = strjoin(arrayfun(@(v) sprintf('%.2g',v),o.testRates,'UniformOutput',false),', ');
for ni = 1:numel(o.networks)
    name = o.networks{ni}; r = a.(name);
    fprintf(fid,['trust_distribution_%s: Distribution of trustworthiness for normal and compromised SMs ' ...
        'in the %s network (N = %d), with P_C = %.2g and P_T = {%s}. ' ...
        'Percentages pool neighbor-to-target evaluations across %d randomized experiments. ' ...
        'Bins are left-closed and right-open, except the final bin, which includes 1.\n\n'], ...
        name,name,r.network.N,o.distributionPC,pt,o.repetitions);
    fprintf(fid,['mean_trustworthiness_%s: Mean trustworthiness of normal and compromised SMs ' ...
        'in the %s network (N = %d), with P_T = {%s} and P_C = %s. ' ...
        'Each parameter combination uses %d randomized experiments of %d interaction rounds. ' ...
        'Points show means of experiment-level mean scores; error bars show one standard deviation ' ...
        'across experiments. All neighboring evaluators are included.\n\n'], ...
        name,name,r.network.N,pt,mat2str(o.attackRates,3),o.repetitions,o.rounds);
end
end
